#!/usr/bin/env python3
"""Build the Splunk API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'HTTP Event Coll.': 'HEC',
    'Cloud Admin Config': 'Cloud Admin',
    'Enterprise REST': 'Ent. REST',
    'Cloud Platform': 'Cloud Plat',
    'Observability Cloud': 'Observability',
    'Enterprise Security': 'Enterprise Security',
    'SOAR Playbook Auto': 'SOAR Auto',
    'Intelligence Mgmt': 'Intel. Mgmt',
}

LINES = [
    {
        "name": 'Platform & Cloud',
        "color": '#65A637',
        "stations": [
        ('Splunk', (270, 200)),
        ('Enterprise REST', (440, 175)),
        ('Cloud Platform', (620, 165)),
        ('Cloud Admin Config', (810, 175)),
        ('HTTP Event Coll.', (980, 200)),
        ],
    },
    {
        "name": 'Security & Operations',
        "color": '#1E5BD0',
        "stations": [
        ('Observability Cloud', (290, 330)),
        ('SOAR', (450, 305)),
        ('Enterprise Security', (640, 305)),
        ('ITSI', (830, 305)),
        ],
    },
    {
        "name": 'Intelligence & Inspect',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('Intelligence Mgmt', (820, 480)),
        ('SOAR Playbook Auto', (910, 555)),
        ('AppInspect', (730, 555)),
        ],
    },
]

URL_OVERRIDES = {
    'Splunk': 'https://apis.apis.io/apis/splunk/splunk/',
    'Enterprise REST': 'https://apis.apis.io/apis/splunk/splunk-enterprise-rest-api/',
    'Cloud Platform': 'https://apis.apis.io/apis/splunk/splunk-cloud-platform-rest-api/',
    'Cloud Admin Config': 'https://apis.apis.io/apis/splunk/splunk-cloud-admin-config-service-api/',
    'HTTP Event Coll.': 'https://apis.apis.io/apis/splunk/splunk-http-event-collector-api/',
    'Observability Cloud': 'https://apis.apis.io/apis/splunk/splunk-observability-cloud-api/',
    'SOAR': 'https://apis.apis.io/apis/splunk/splunk-soar-rest-api/',
    'Enterprise Security': 'https://apis.apis.io/apis/splunk/splunk-enterprise-security-api/',
    'ITSI': 'https://apis.apis.io/apis/splunk/splunk-itsi-rest-api/',
    'Intelligence Mgmt': 'https://apis.apis.io/apis/splunk/splunk-intelligence-management-api/',
    'SOAR Playbook Auto': 'https://apis.apis.io/apis/splunk/splunk-soar-playbook-automation-api/',
    'AppInspect': 'https://apis.apis.io/apis/splunk/splunk-appinspect-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Splunk API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: splunk/openapi · github.com/api-evangelist/splunk',
        out_dir=Path(__file__).resolve().parent,
        out_basename='splunk-subway-map',
        provider_id='splunk',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
